{
 "about": {
  "channels": [
   "conda-forge",
   "defaults"
  ],
  "conda_build_version": "3.17.8",
  "conda_private": false,
  "conda_version": "4.6.14",
  "dev_url": "https://github.com/jgliss/geonum",
  "doc_url": "https://geonum.readthedocs.io/",
  "env_vars": {
   "CIO_TEST": "<not set>"
  },
  "extra": {
   "copy_test_source_files": true,
   "final": true,
   "recipe-maintainers": [
    "jgliss"
   ]
  },
  "home": "https://github.com/jgliss/geonum",
  "identifiers": [],
  "keywords": [],
  "license": "GPL-3.0",
  "license_family": "GPL",
  "license_file": "LICENSE",
  "root_pkgs": [
   "ncurses 6.1 hf484d3e_1002",
   "sqlite 3.26.0 h67949de_1001",
   "tqdm 4.32.1 py_0",
   "perl 5.26.2 h516909a_1006",
   "idna 2.8 py37_1000",
   "ipython_genutils 0.2.0 py_1",
   "filelock 3.0.10 py_0",
   "pysocks 1.7.0 py37_0",
   "conda 4.6.14 py37_0",
   "libarchive 3.3.3 hc3f970e_1004",
   "readline 7.0 hf8c457e_1001",
   "beautifulsoup4 4.7.1 py37_1001",
   "attrs 19.1.0 py_0",
   "libxml2 2.9.9 h13577e0_0",
   "libiconv 1.15 h516909a_1005",
   "git 2.21.0 pl526h2882143_0",
   "krb5 1.16.3 h05b26f9_1001",
   "psutil 5.6.2 py37h516909a_0",
   "bzip2 1.0.6 h14c3975_1002",
   "zlib 1.2.11 h14c3975_1004",
   "anaconda-client 1.7.2 py_0",
   "zstd 1.3.3 1",
   "pyopenssl 19.0.0 py37_0",
   "clyent 1.2.2 py_1",
   "setuptools 41.0.1 py37_0",
   "openssl 1.1.1b h14c3975_1",
   "cffi 1.12.3 py37h8022711_0",
   "pytz 2019.1 py_0",
   "six 1.12.0 py37_1000",
   "chardet 3.0.4 py37_1003",
   "jinja2 2.10.1 py_0",
   "conda-build 3.17.8 py37_1",
   "python 3.7.3 h5b0a415_0",
   "python-libarchive-c 2.8 py37_1004",
   "ca-certificates 2019.3.9 hecc5488_0",
   "gosu 1.10 h81701ea_1001",
   "certifi 2019.3.9 py37_0",
   "asn1crypto 0.24.0 py37_1003",
   "python-dateutil 2.8.0 py_0",
   "tk 8.6.9 h84994c4_1001",
   "decorator 4.4.0 py_0",
   "lzo 2.10 h14c3975_1000",
   "lz4-c 1.8.3 he1b5a44_1001",
   "libssh2 1.8.2 h22169c7_2",
   "jsonschema 3.0.1 py37_0",
   "tini 0.18.0 h14c3975_1001",
   "expat 2.2.5 hf484d3e_1002",
   "jupyter_core 4.4.0 py_0",
   "pycosat 0.6.3 py37h14c3975_1001",
   "pyyaml 5.1 py37h14c3975_0",
   "requests 2.22.0 py37_0",
   "cryptography 2.6.1 py37h72c5cf5_0",
   "libedit 3.1.20170329 hf8c457e_1001",
   "yaml 0.1.7 h14c3975_1001",
   "traitlets 4.3.2 py37_1000",
   "patchelf 0.9 hf484d3e_1004",
   "wheel 0.33.4 py37_0",
   "libstdcxx-ng 8.2.0 hdf63c60_1",
   "pip 19.1 py37_0",
   "icu 58.2 hf484d3e_1000",
   "libffi 3.2.1 he1b5a44_1006",
   "ruamel_yaml 0.15.71 py37h14c3975_1000",
   "py-lief 0.9.0 py37hf484d3e_0",
   "soupsieve 1.9.1 py37_0",
   "libcurl 7.64.1 hda55be3_0",
   "liblief 0.9.0 h1532aa0_0",
   "curl 7.64.1 hf8cf82a_0",
   "gettext 0.19.8.1 hc5be6a0_1002",
   "nbformat 4.4.0 py_1",
   "glob2 0.6 py_0",
   "pycparser 2.19 py37_1",
   "libgcc-ng 8.2.0 hdf63c60_1",
   "xz 5.2.4 h14c3975_1001",
   "pyrsistent 0.15.2 py37h516909a_0",
   "urllib3 1.24.3 py37_0",
   "conda-env 2.6.0 1",
   "pkginfo 1.5.0.1 py_0",
   "markupsafe 1.1.1 py37h14c3975_0",
   "conda-forge-ci-setup 2.3.1 py37_0",
   "click 7.0 py_0"
  ],
  "summary": "Toolbox for 3D geonumerical calculations",
  "tags": []
 },
 "conda_build_config": {
  "build_number_decrement": "0",
  "c_compiler": "gcc",
  "channel_sources": "conda-forge,defaults",
  "channel_targets": "conda-forge main",
  "cpu_optimization_target": "nocona",
  "cran_mirror": "https://cran.r-project.org",
  "cxx_compiler": "gxx",
  "docker_image": "condaforge/linux-anvil-comp7",
  "extend_keys": [
   "ignore_build_only_deps",
   "extend_keys",
   "pin_run_as_build",
   "ignore_version"
  ],
  "fortran_compiler": "gfortran",
  "ignore_build_only_deps": [
   "numpy",
   "python"
  ],
  "lua": "5",
  "numpy": "1.11",
  "perl": "5.26.0",
  "pin_run_as_build": {
   "python": {
    "max_pin": "x.x",
    "min_pin": "x.x"
   },
   "r-base": {
    "max_pin": "x.x.x",
    "min_pin": "x.x.x"
   }
  },
  "python": "3.7",
  "r_base": "3.5",
  "target_platform": "linux-64"
 },
 "files": [
  "lib/python3.7/site-packages/geonum-1.4.3.dist-info/INSTALLER",
  "lib/python3.7/site-packages/geonum-1.4.3.dist-info/LICENSE",
  "lib/python3.7/site-packages/geonum-1.4.3.dist-info/METADATA",
  "lib/python3.7/site-packages/geonum-1.4.3.dist-info/RECORD",
  "lib/python3.7/site-packages/geonum-1.4.3.dist-info/WHEEL",
  "lib/python3.7/site-packages/geonum/__init__.py",
  "lib/python3.7/site-packages/geonum/atmosphere.py",
  "lib/python3.7/site-packages/geonum/elevationprofile.py",
  "lib/python3.7/site-packages/geonum/exceptions.py",
  "lib/python3.7/site-packages/geonum/geopoint.py",
  "lib/python3.7/site-packages/geonum/geosetup.py",
  "lib/python3.7/site-packages/geonum/geovector3d.py",
  "lib/python3.7/site-packages/geonum/helpers.py",
  "lib/python3.7/site-packages/geonum/local_topo_data/README.rst",
  "lib/python3.7/site-packages/geonum/mapping.py",
  "lib/python3.7/site-packages/geonum/processing.py",
  "lib/python3.7/site-packages/geonum/test/__init__.py",
  "lib/python3.7/site-packages/geonum/test/markers.py",
  "lib/python3.7/site-packages/geonum/test/test_base_classes.py",
  "lib/python3.7/site-packages/geonum/test/test_elevationprofile.py",
  "lib/python3.7/site-packages/geonum/test/test_srtm_database.py",
  "lib/python3.7/site-packages/geonum/test/test_topodata.py",
  "lib/python3.7/site-packages/geonum/topoaccessbase.py",
  "lib/python3.7/site-packages/geonum/topodata.py",
  "lib/python3.7/site-packages/geonum/topodataaccess.py"
 ],
 "index": {
  "arch": "x86_64",
  "build": "py37_0",
  "build_number": 0,
  "depends": [
   "basemap",
   "latlon23",
   "netcdf4",
   "pytest",
   "python >=3.7,<3.8.0a0",
   "scipy",
   "srtm.py"
  ],
  "license": "GPL-3.0",
  "license_family": "GPL",
  "name": "geonum",
  "platform": "linux",
  "subdir": "linux-64",
  "timestamp": 1558286147344,
  "version": "1.4.3"
 },
 "metadata_version": 1,
 "name": "geonum",
 "raw_recipe": "{% set name = \"geonum\" %}\n{% set version = \"1.4.3\" %}\n\npackage:\n  name: \"{{ name|lower }}\"\n  version: \"{{ version }}\"\n\nsource:\n  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz\n  sha256: f393389a0c22664613075cd22e784aee264e7ea4c4d8aa2accf2b2896c826150\n\nbuild:\n  number: 0\n  script: \"{{ PYTHON }} -m pip install . -vv\"\n\nrequirements:\n  host:\n    - pip\n    - python\n  run:\n    - python\n    - scipy\n    - basemap\n    - netcdf4\n    - latlon23\n    - pytest\n    - srtm.py\n\ntest:\n  imports:\n    - geonum\n    - geonum.test\n\nabout:\n  home: https://github.com/jgliss/geonum\n  license: GPL-3.0\n  license_family: GPL\n  license_file: LICENSE\n  summary: Toolbox for 3D geonumerical calculations\n  doc_url: https://geonum.readthedocs.io/\n  dev_url: https://github.com/jgliss/geonum\n\nextra:\n  recipe-maintainers:\n    - jgliss\n",
 "rendered_recipe": {
  "about": {
   "dev_url": "https://github.com/jgliss/geonum",
   "doc_url": "https://geonum.readthedocs.io/",
   "home": "https://github.com/jgliss/geonum",
   "license": "GPL-3.0",
   "license_family": "GPL",
   "license_file": "LICENSE",
   "summary": "Toolbox for 3D geonumerical calculations"
  },
  "build": {
   "number": "0",
   "script": "/home/conda/feedstock_root/build_artifacts/geonum_1558286084196/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python -m pip install . -vv",
   "string": "py37_0"
  },
  "extra": {
   "copy_test_source_files": true,
   "final": true,
   "recipe-maintainers": [
    "jgliss"
   ]
  },
  "package": {
   "name": "geonum",
   "version": "1.4.3"
  },
  "requirements": {
   "host": [
    "bzip2 1.0.6 h14c3975_1002",
    "ca-certificates 2019.3.9 hecc5488_0",
    "certifi 2019.3.9 py37_0",
    "libffi 3.2.1 he1b5a44_1006",
    "libgcc-ng 8.2.0 hdf63c60_1",
    "libstdcxx-ng 8.2.0 hdf63c60_1",
    "ncurses 6.1 hf484d3e_1002",
    "openssl 1.1.1b h14c3975_1",
    "pip 19.1 py37_0",
    "python 3.7.3 h5b0a415_0",
    "readline 7.0 hf8c457e_1001",
    "setuptools 41.0.1 py37_0",
    "sqlite 3.26.0 h67949de_1001",
    "tk 8.6.9 h84994c4_1001",
    "wheel 0.33.4 py37_0",
    "xz 5.2.4 h14c3975_1001",
    "zlib 1.2.11 h14c3975_1004"
   ],
   "run": [
    "basemap",
    "latlon23",
    "netcdf4",
    "pytest",
    "python >=3.7,<3.8.0a0",
    "scipy",
    "srtm.py"
   ]
  },
  "source": {
   "sha256": "f393389a0c22664613075cd22e784aee264e7ea4c4d8aa2accf2b2896c826150",
   "url": "https://pypi.io/packages/source/g/geonum/geonum-1.4.3.tar.gz"
  },
  "test": {
   "imports": [
    "geonum",
    "geonum.test"
   ]
  }
 },
 "version": "1.4.3"
}