{
 "about": {
  "channels": [
   "conda-forge",
   "defaults",
   "https://conda.anaconda.org/conda-forge"
  ],
  "conda_build_version": "3.19.1",
  "conda_private": false,
  "conda_version": "4.8.3",
  "env_vars": {
   "CIO_TEST": "<not set>"
  },
  "extra": {
   "copy_test_source_files": true,
   "final": true,
   "recipe-maintainers": [
    "bjlittle",
    "ocefpaf",
    "pelson"
   ]
  },
  "home": "https://scitools.org.uk/cf-units/docs/latest/",
  "identifiers": [],
  "keywords": [],
  "license": "LGPL-3.0",
  "license_file": "COPYING.LESSER",
  "root_pkgs": [
   "importlib-metadata 1.5.0 py37hc8dfbb8_1",
   "pysocks 1.7.1 py37hc8dfbb8_1",
   "python-dateutil 2.8.1 py_0",
   "zstd 1.4.4 h3b9ef0a_2",
   "attrs 19.3.0 py_0",
   "jsonschema 3.2.0 py37hc8dfbb8_1",
   "liblief 0.9.0 hf8a498c_1",
   "psutil 5.7.0 py37h8f50634_1",
   "clyent 1.2.2 py_1",
   "py-lief 0.9.0 py37he1b5a44_1",
   "wheel 0.34.2 py_1",
   "pycparser 2.20 py_0",
   "perl 5.26.2 h516909a_1006",
   "urllib3 1.25.7 py37hc8dfbb8_1",
   "su-exec 0.2 h14c3975_1001",
   "soupsieve 1.9.4 py37hc8dfbb8_1",
   "ipython_genutils 0.2.0 py_1",
   "zipp 3.1.0 py_0",
   "glob2 0.7 py_0",
   "tqdm 4.43.0 py_0",
   "markupsafe 1.1.1 py37h8f50634_1",
   "pytz 2019.3 py_0",
   "libstdcxx-ng 9.2.0 hdf63c60_2",
   "cffi 1.14.0 py37hd463f26_0",
   "idna 2.9 py_1",
   "tini 0.18.0 h14c3975_1001",
   "libgomp 9.2.0 h24d8f2e_2",
   "jinja2 2.11.1 py_0",
   "ruamel_yaml 0.15.80 py37h8f50634_1001",
   "icu 64.2 he1b5a44_1",
   "chardet 3.0.4 py37hc8dfbb8_1006",
   "ld_impl_linux-64 2.34 h53a641e_0",
   "python_abi 3.7 1_cp37m",
   "curl 7.68.0 hf8cf82a_0",
   "conda 4.8.3 py37hc8dfbb8_1",
   "patch 2.7.6 h14c3975_1001",
   "python 3.7.6 h357f687_4_cpython",
   "lz4-c 1.8.3 he1b5a44_1001",
   "libffi 3.2.1 he1b5a44_1007",
   "conda-package-handling 1.6.0 py37h8f50634_2",
   "pyyaml 5.3.1 py37h8f50634_0",
   "libcurl 7.68.0 hda55be3_0",
   "importlib_metadata 1.5.0 1",
   "jupyter_core 4.6.3 py37hc8dfbb8_1",
   "traitlets 4.3.3 py37hc8dfbb8_1",
   "libedit 3.1.20170329 hf8c457e_1001",
   "gettext 0.19.8.1 hc5be6a0_1002",
   "anaconda-client 1.7.2 py_0",
   "nbformat 5.0.4 py_0",
   "setuptools 46.0.0 py37hc8dfbb8_2",
   "libxml2 2.9.10 hee79883_0",
   "certifi 2019.11.28 py37hc8dfbb8_1",
   "pkginfo 1.5.0.1 py_0",
   "readline 8.0 hf8c457e_0",
   "krb5 1.16.4 h2fd8d38_0",
   "conda-build 3.19.1 py37hc8dfbb8_0",
   "pcre 8.44 he1b5a44_0",
   "yaml 0.2.2 h516909a_1",
   "libgcc-ng 9.2.0 h24d8f2e_2",
   "zlib 1.2.11 h516909a_1006",
   "sqlite 3.30.1 hcee41ef_0",
   "patchelf 0.10 he1b5a44_0",
   "_openmp_mutex 4.5 0_gnu",
   "expat 2.2.9 he1b5a44_2",
   "git 2.25.0 pl526hce37bd2_0",
   "libarchive 3.3.3 hc47fbbf_1007",
   "filelock 3.0.10 py_0",
   "pycosat 0.6.3 py37h8f50634_1004",
   "_libgcc_mutex 0.1 conda_forge",
   "beautifulsoup4 4.8.2 py37_0",
   "pip 20.0.2 py_2",
   "pyrsistent 0.15.7 py37h8f50634_1",
   "libiconv 1.15 h516909a_1006",
   "bzip2 1.0.8 h516909a_2",
   "ncurses 6.1 hf484d3e_1002",
   "python-libarchive-c 2.9 py37_0",
   "decorator 4.4.2 py_0",
   "six 1.14.0 py_1",
   "openssl 1.1.1e h516909a_0",
   "ca-certificates 2019.11.28 hecc5488_0",
   "requests 2.23.0 pyh8c360ce_2",
   "libssh2 1.8.2 h22169c7_2",
   "ripgrep 11.0.2 h516909a_3",
   "tk 8.6.10 hed695b0_0",
   "xz 5.2.4 h516909a_1002",
   "cryptography 2.8 py37hb09aad4_2",
   "pyopenssl 19.1.0 py_1",
   "lzo 2.10 h14c3975_1000",
   "conda-forge-ci-setup 2.6.0 py37hc8dfbb8_0",
   "click 7.1.1 pyh8c360ce_0",
   "conda-env 2.6.0 1"
  ],
  "summary": "Units of measure as required by the Climate and Forecast (CF) metadata conventions.",
  "tags": []
 },
 "conda_build_config": {
  "CI": "azure",
  "c_compiler": "gcc",
  "c_compiler_version": "7",
  "channel_sources": "conda-forge,defaults",
  "channel_targets": "conda-forge main",
  "cpu_optimization_target": "nocona",
  "cran_mirror": "https://cran.r-project.org",
  "cxx_compiler": "gxx",
  "docker_image": "condaforge/linux-anvil-comp7",
  "extend_keys": [
   "pin_run_as_build",
   "extend_keys",
   "ignore_version",
   "ignore_build_only_deps"
  ],
  "fortran_compiler": "gfortran",
  "ignore_build_only_deps": [
   "python",
   "numpy"
  ],
  "lua": "5",
  "numpy": "1.14",
  "perl": "5.26.0",
  "pin_run_as_build": {
   "python": {
    "max_pin": "x.x",
    "min_pin": "x.x"
   },
   "r-base": {
    "max_pin": "x.x",
    "min_pin": "x.x"
   }
  },
  "python": "3.6.* *_cpython",
  "r_base": "3.5",
  "target_platform": "linux-64"
 },
 "files": [
  "lib/python3.6/site-packages/cf_units-2.1.4.dist-info/COPYING",
  "lib/python3.6/site-packages/cf_units-2.1.4.dist-info/COPYING.LESSER",
  "lib/python3.6/site-packages/cf_units-2.1.4.dist-info/INSTALLER",
  "lib/python3.6/site-packages/cf_units-2.1.4.dist-info/METADATA",
  "lib/python3.6/site-packages/cf_units-2.1.4.dist-info/RECORD",
  "lib/python3.6/site-packages/cf_units-2.1.4.dist-info/WHEEL",
  "lib/python3.6/site-packages/cf_units/__init__.py",
  "lib/python3.6/site-packages/cf_units/_udunits2.cpython-36m-x86_64-linux-gnu.so",
  "lib/python3.6/site-packages/cf_units/_udunits2_parser/__init__.py",
  "lib/python3.6/site-packages/cf_units/_udunits2_parser/compile.py",
  "lib/python3.6/site-packages/cf_units/_udunits2_parser/graph.py",
  "lib/python3.6/site-packages/cf_units/_udunits2_parser/parser/__init__.py",
  "lib/python3.6/site-packages/cf_units/_udunits2_parser/parser/udunits2Lexer.py",
  "lib/python3.6/site-packages/cf_units/_udunits2_parser/parser/udunits2Parser.py",
  "lib/python3.6/site-packages/cf_units/_udunits2_parser/parser/udunits2ParserVisitor.py",
  "lib/python3.6/site-packages/cf_units/_version.py",
  "lib/python3.6/site-packages/cf_units/config.py",
  "lib/python3.6/site-packages/cf_units/conftest.py",
  "lib/python3.6/site-packages/cf_units/etc/site.cfg",
  "lib/python3.6/site-packages/cf_units/etc/site.cfg.template",
  "lib/python3.6/site-packages/cf_units/tests/__init__.py",
  "lib/python3.6/site-packages/cf_units/tests/integration/__init__.py",
  "lib/python3.6/site-packages/cf_units/tests/integration/test__num2date_to_nearest_second.py",
  "lib/python3.6/site-packages/cf_units/tests/integration/test_date2num.py",
  "lib/python3.6/site-packages/cf_units/tests/test_coding_standards.py",
  "lib/python3.6/site-packages/cf_units/tests/test_tex.py",
  "lib/python3.6/site-packages/cf_units/tests/test_unit.py",
  "lib/python3.6/site-packages/cf_units/tests/unit/__init__.py",
  "lib/python3.6/site-packages/cf_units/tests/unit/test__udunits2.py",
  "lib/python3.6/site-packages/cf_units/tex.py",
  "lib/python3.6/site-packages/cf_units/util.py"
 ],
 "index": {
  "arch": "x86_64",
  "build": "py36h785e9b2_0",
  "build_number": 0,
  "depends": [
   "antlr-python-runtime 4.7.2.*",
   "cftime",
   "libgcc-ng >=7.3.0",
   "numpy >=1.14.6,<2.0a0",
   "python >=3.6,<3.7.0a0",
   "python_abi 3.6.* *_cp36m",
   "six",
   "udunits2 >=2.2.27.6,<2.3.0a0"
  ],
  "license": "LGPL-3.0",
  "name": "cf-units",
  "platform": "linux",
  "subdir": "linux-64",
  "timestamp": 1584801011372,
  "version": "2.1.4"
 },
 "metadata_version": 1,
 "name": "cf-units",
 "raw_recipe": "{% set version = \"2.1.4\" %}\n\npackage:\n  name: cf-units\n  version: {{ version }}\n\nsource:\n  url: https://pypi.io/packages/source/c/cf-units/cf-units-{{ version }}.tar.gz\n  sha256: 25f81ad994af30713ee8f5ef18ffddd83c6ec1ac308e1bd89d45de9d2e0f1c31\n\nbuild:\n  number: 0\n  skip: true  # [win and py2k]\n\nrequirements:\n  build:\n    - {{ compiler('c') }}\n  host:\n    - python\n    - pip\n    - numpy\n    - cython\n    - udunits2\n    # It isn't clear that this really is needed, but it is listed in setup.py.\n    - pytest-runner\n  run:\n    - {{ pin_compatible('udunits2', max_pin='x.x') }}\n    - python\n    - cftime\n    - {{ pin_compatible('numpy') }}\n    - antlr-python-runtime 4.7.2.*  # [py3k]\n    - six\n\ntest:\n  requires:\n    - pytest\n    - pip\n  imports:\n    - cf_units\n  commands:\n    - pip check\n    - pytest --pyargs cf_units                                   # [not (win and py2k)]\n      # On win py2 we are getting an unexpected test failure. See also\n      # https://github.com/SciTools/cf-units/issues/148.\n    - pytest --pyargs cf_units -k=\"-test_read_xml_invalid_path\"  # [win and py2k]\n\nabout:\n  home: https://scitools.org.uk/cf-units/docs/latest/\n  license: LGPL-3.0\n  license_file: COPYING.LESSER\n  summary: Units of measure as required by the Climate and Forecast (CF) metadata conventions.\n\nextra:\n  recipe-maintainers:\n    - bjlittle\n    - ocefpaf\n    - pelson\n",
 "rendered_recipe": {
  "about": {
   "home": "https://scitools.org.uk/cf-units/docs/latest/",
   "license": "LGPL-3.0",
   "license_file": "COPYING.LESSER",
   "summary": "Units of measure as required by the Climate and Forecast (CF) metadata conventions."
  },
  "build": {
   "number": "0",
   "string": "py36h785e9b2_0"
  },
  "extra": {
   "copy_test_source_files": true,
   "final": true,
   "recipe-maintainers": [
    "bjlittle",
    "ocefpaf",
    "pelson"
   ]
  },
  "package": {
   "name": "cf-units",
   "version": "2.1.4"
  },
  "requirements": {
   "build": [
    "_libgcc_mutex 0.1 conda_forge",
    "_openmp_mutex 4.5 0_gnu",
    "binutils_impl_linux-64 2.34 h53a641e_0",
    "binutils_linux-64 2.34 hc952b39_18",
    "gcc_impl_linux-64 7.3.0 hd420e75_5",
    "gcc_linux-64 7.3.0 h553295d_18",
    "ld_impl_linux-64 2.34 h53a641e_0",
    "libgcc-ng 9.2.0 h24d8f2e_2",
    "libgomp 9.2.0 h24d8f2e_2",
    "libstdcxx-ng 9.2.0 hdf63c60_2"
   ],
   "host": [
    "_libgcc_mutex 0.1 conda_forge",
    "_openmp_mutex 4.5 1_llvm",
    "attrs 19.3.0 py_0",
    "ca-certificates 2019.11.28 hecc5488_0",
    "certifi 2019.11.28 py36h9f0ad1d_1",
    "cython 0.29.15 py36h831f99a_1",
    "expat 2.2.9 he1b5a44_2",
    "importlib-metadata 1.5.0 py36h9f0ad1d_1",
    "importlib_metadata 1.5.0 1",
    "ld_impl_linux-64 2.34 h53a641e_0",
    "libblas 3.8.0 16_openblas",
    "libcblas 3.8.0 16_openblas",
    "libffi 3.2.1 he1b5a44_1007",
    "libgcc-ng 9.2.0 h24d8f2e_2",
    "libgfortran-ng 7.3.0 hdf63c60_5",
    "liblapack 3.8.0 16_openblas",
    "libopenblas 0.3.9 h5ec1e0e_0",
    "libstdcxx-ng 9.2.0 hdf63c60_2",
    "llvm-openmp 9.0.1 hc9558a2_2",
    "more-itertools 8.2.0 py_0",
    "ncurses 6.1 hf484d3e_1002",
    "numpy 1.14.6 py36h95a1406_1201",
    "openssl 1.1.1e h516909a_0",
    "packaging 20.1 py_0",
    "pip 20.0.2 py_2",
    "pluggy 0.12.0 py_0",
    "py 1.8.1 py_0",
    "pyparsing 2.4.6 py_0",
    "pytest 5.4.1 py36h9f0ad1d_0",
    "pytest-runner 5.2 py_0",
    "python 3.6.10 h9d8adfe_1009_cpython",
    "python_abi 3.6 1_cp36m",
    "readline 8.0 hf8c457e_0",
    "setuptools 46.0.0 py36h9f0ad1d_2",
    "six 1.14.0 py_1",
    "sqlite 3.30.1 hcee41ef_0",
    "tk 8.6.10 hed695b0_0",
    "udunits2 2.2.27.6 h4e0c4b3_1001",
    "wcwidth 0.1.8 py_0",
    "wheel 0.34.2 py_1",
    "xz 5.2.4 h516909a_1002",
    "zipp 3.1.0 py_0",
    "zlib 1.2.11 h516909a_1006"
   ],
   "run": [
    "antlr-python-runtime 4.7.2.*",
    "cftime",
    "libgcc-ng >=7.3.0",
    "numpy >=1.14.6,<2.0a0",
    "python >=3.6,<3.7.0a0",
    "python_abi 3.6.* *_cp36m",
    "six",
    "udunits2 >=2.2.27.6,<2.3.0a0"
   ]
  },
  "source": {
   "sha256": "25f81ad994af30713ee8f5ef18ffddd83c6ec1ac308e1bd89d45de9d2e0f1c31",
   "url": "https://pypi.io/packages/source/c/cf-units/cf-units-2.1.4.tar.gz"
  },
  "test": {
   "commands": [
    "pip check",
    "pytest --pyargs cf_units"
   ],
   "imports": [
    "cf_units"
   ],
   "requires": [
    "pip",
    "pytest"
   ]
  }
 },
 "version": "2.1.4"
}